//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTCM_EcoMart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAccount()
        {
            this.tblWishlists = new HashSet<tblWishlist>();
            this.tblBills = new HashSet<tblBill>();
        }
    
        public string Account_ID { get; set; }
        public string Customer_email { get; set; }
        public string Customer_password { get; set; }
        public string Customer_name { get; set; }
        public string Customer_Address { get; set; }
        public byte Customer_gender { get; set; }
        public int Customer_phone { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public bool User_Role { get; set; }
        public string ID_wishlist { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWishlist> tblWishlists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBill> tblBills { get; set; }
    }
}
