//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTCM_EcoMart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSale
    {
        public string Sale_ID { get; set; }
        public string product_ID { get; set; }
        public System.DateTime Start_day { get; set; }
        public System.DateTime End_day { get; set; }
        public Nullable<double> Discount { get; set; }
    
        public virtual tblProduct tblProduct { get; set; }
    }
}
