//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTCM_EcoMart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWishlist_details
    {
        public string wishlist_details_ID { get; set; }
        public string ID_wishlist { get; set; }
        public string product_ID { get; set; }
        public Nullable<long> quantity { get; set; }
    
        public virtual tblProduct tblProduct { get; set; }
        public virtual tblWishlist tblWishlist { get; set; }
    }
}
